spring.application.name=app

spring.datasource.url=jdbc:postgresql://interchange.proxy.rlwy.net:20246/railway?sslmode=require&ssl=true&connectTimeout=30&socketTimeout=60

spring.datasource.username=postgres
spring.datasource.password=leFAvnbRyGeqXBezNlhgIdvoNBoxyGHB

# HikariCP connection pool timeout
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Razorpay
razorpay.key.id=rzp_test_TXDBWLptRpBdn3
razorpay.key.secret=ltG4AD609lP40LRVgk7j7Fgb